Vagrant.configure("2") do |config|
  config.vm.define "trouble" do |tr|
    tr.vm.box = "mntlab-troubleshooting"
    tr.vm.hostname = "kazak-trouble"
    tr.vm.network "private_network", ip: "192.168.56.100"
    tr.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    tr.vm.provision "shell", path: "provision_indian_recover.sh", privileged: false
  end

end
