Vagrant.configure("2") do |config|
#
# creating and configuring VM for nginx
#
  config.vm.define "web" do |web|
    web.vm.box = "sbeliakou/centos"
    web.vm.hostname = "kazak-nginx"
    web.vm.network "private_network", ip: "192.168.56.22"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    web.vm.provision "shell", path: "provision.sh", privileged: false
  end
end
